### ISSUE TITLE
Compiler-macro error on loading in Spacemacs

### ISSUE THREAD

**Issue by BliznyukNM** [GDQuest/emacs-gdscript-mode#34] opened 2020-03-04 08:56 UTC
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

Loading of gdscript-mode ends with errors:

`Compiler-macro error for gdscript-syntax-comment-or-string-p: (wrong-type-argument listp ppss)`

`Compiler-macro error for gdscript-syntax-count-quotes: (wrong-type-argument number-or-marker-p (point))`

`Compiler-macro error for gdscript-syntax-count-quotes: (wrong-type-argument number-or-marker-p str-start-pos)`

Highlighting works fine, but no auto-completion and code formatting.

I'm using emacs 26.3. Bug reproduced on develop and master branch of spacemacs.

**Comment by ofrank123** [comment] 2020-03-04 10:23
I'll look into this later today.  Going to test in 26.3 first to check if its a version error or a spacemacs.  We do most of the development on emacs 27, but once we set up the CI PRs/commits should automatically be tested on 26 as well.

**Comment by BliznyukNM** [comment] 2020-03-04 11:03
Checked on Emacs 27.0.90, had same errors.

**Comment by ofrank123** [comment] 2020-03-04 11:11
OK, I'll assume its a spacemacs issue for now and go from there.  Thanks for testing on 27.

**Comment by BliznyukNM** [comment] 2020-03-04 11:28
Same issue but it was closed.
#21

**Comment by NathanLovato** [comment] 2020-03-04 13:24
It was closed because it was fixed for me in a previous commit. I wonder what's the issue with Spacemacs, the package works well in vanilla and doom emacs.

If you have an idea on how to fix it, PRs are welcome.

**Comment by ChrisMGeo** [comment] 2020-03-15 22:57
I'm also facing this problem. I am using emacs 26.3 and tried using the current repository (The previous one I used was 7 days ago), but the problem still persists.

**Comment by jcs090218** [comment] 2020-03-28 05:57
I have the same error using vanilla Emacs. 😕

**Comment by NathanLovato** [comment] 2020-03-28 13:05
I have trouble replicating the issue right now, and limited time to work on this package as well. PRs are most welcome!

**Comment by NathanLovato** [comment] 2020-03-28 17:07
I tried with:

- Emacs 26.3 and 27.0.90 vanilla, with only the gdscript-mode package
- Spacemacs
- Doom emacs

I could only reproduce it in Spacemacs with emacs 26.3, and I only get the first error message:

```elisp
Compiler-macro error for gdscript-syntax-comment-or-string-p: (wrong-type-argument listp ppss)
```

**Comment by NathanLovato** [comment] 2020-03-28 18:09
Running the debugger, this is due to line 210 in `gdscript-indent-and-nav.el`:

```elisp
     ((let ((start (unless (gdscript-syntax-comment-or-string-p ppss)
                     (gdscript-info-line-ends-backslash-p
                      (1- (line-number-at-pos))))))
```

This `ppss` is the cursor position when calling `gdscript-indent-context`:

```elisp
  (let ((ppss (save-excursion
                (beginning-of-line)
                (syntax-ppss))))
```

**Comment by NathanLovato** [comment] 2020-03-28 18:23
The latest commit, along with fixes from previous commits, addresses all the load errors above for me.  Could you pull the latest master and confirm that's the case for you too? If not, could you please:

- Paste the error message you get when launching emacs normally
- Run `emacs --debug-init` (or run your emacs with the `--debug-init` option) and copy the complete debug backtrace

Thanks!

**Comment by NathanLovato** [comment] 2020-03-30 14:18
I'll close the issue for now as I can't reproduce it anymore. If you still have it, could you please leave me the information above?

Also if you get a new error, you can open a new issue.

Thanks for the report!

**Closed by NathanLovato** 2020-03-30 14:18 UTC
Labels: bug, good first issue

**Comment by jcs090218** [comment] 2020-03-31 02:49
@NathanLovato Thanks for resolving this issue! Just want to say thank! :)
